name: your_project_name
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.0.0  # 최신 버전으로 업데이트 할 수 있습니다.
  photo_view: ^0.14.0
  http: ^0.13.5
  flutter_dotenv: ^5.0.2

dev_dependencies:  # flutter_launcher_icons는 dev_dependencies에 포함
  flutter_launcher_icons: "^0.10.0"

flutter_icons:  # flutter_icons 설정은 dev_dependencies 바깥에 위치해야 함
  android: true
  ios: true
  image_path: "assets/images/ekgapp.png"

flutter:
  uses-material-design: true

  assets:
    - config.env
    - assets/images/class/sinus_rhythm.png
    - assets/images/class/sinus_bradycardia.png
    - assets/images/class/sinus_tachycardia.png
    - assets/images/class/atrial_premature_contraction.png
    - assets/images/class/ventricular_premature_contraction.png
    - assets/images/class/first_degree_block.png
    - assets/images/class/second_degree_block_(mobitz_type_i).png
    - assets/images/class/second_degree_block_(mobitz_type_ii).png
    - assets/images/class/complete_degree_block.png
    - assets/images/class/atrial_flutter.png
    - assets/images/class/atrial_fibrillation.png
    - assets/images/class/ventricular_tachycardia.png
    - assets/images/class/ventricular_fibrillation.png
    - assets/images/class/sustain_vt.png
    - assets/images/class/avnrt.png
    - assets/images/class/avrt.png
    - assets/images/class/junctional_escape_rhythm.png
    - assets/images/class/accelerated_idioventricular_rhythm.png
    - assets/images/class/left_bundle_branch_block.png
    - assets/images/class/right_bundle_branch_block.png
    - assets/images/class/anterior_fascicular_block.png
    - assets/images/class/posterior_fascicular_block.png
    - assets/images/class/trifasicular_block.png
    - assets/images/class/hyperkalemia.png
    - assets/images/class/v_pacemaker_rhythm.png
    - assets/images/class/a_pacemaker_rhythm.png
    - assets/images/class/brugada_syndrome.png
    - assets/images/class/long_qt_syndrome.png
    - assets/images/class/asystole.png
    - assets/images/class/wellens_syndrome.png
    - assets/images/class/aortic_dissection.png
    - assets/images/class/stress_induced_cmp.png
    - assets/images/class/inferior_infarction_(rca).png
    - assets/images/class/anterior_infarction_(lad).png
    - assets/images/class/old_mi.png
    - assets/images/class/left_ventricle_hypertrophy.png
    - assets/images/class/early_repolarization_syndrome.png
    - assets/images/class/septic_shock.png
    - assets/images/mLCx_total_STEMI_dominant.png
    - assets/images/Junction_with_RCAinfaction.png
    - assets/images/ecgreadingsteps.png
    - assets/images/ecgleadposition.png
    - assets/images/ecgcardiacaxis.png
    - assets/images/axis.png
    - assets/images/ecgwaveform.png
    - assets/images/stemi_territory.png
    - assets/images/evolution_ami.png
    - assets/images/quiz/sinus_tachycardia.png
    - assets/images/quiz/sinus_tachycardia2.png
    - assets/images/quiz/sinus_rhythm.png
    - assets/images/quiz/sinus_bradycardia.png
    - assets/images/quiz/first_AVblock.png
    - assets/images/quiz/RBBB3(2).png
    - assets/images/quiz/Complete_block_LBBB(4).png
    - assets/images/quiz/AVRT_right(6).png
    - assets/images/quiz/vfib(9).png
    - assets/images/quiz/LBBB2(10).png
    - assets/images/quiz/afib_LAFB(14).png
    - assets/images/quiz/Trifasicular_block(19).png
    - assets/images/quiz/Junctional_tachycardia(20).png
    - assets/images/quiz/Afib_rvr(21).png
    - assets/images/quiz/RBBB_with_afib(25).png
    - assets/images/quiz/RBBB_Brady(26).png
    - assets/images/quiz/SlowVTy(27).png
    - assets/images/quiz/afib_rvr(29).png
    - assets/images/quiz/Anterior_STEMI(30).png
    - assets/images/quiz/APC(31).png
    - assets/images/quiz/pLAD_STEMI(32).png
    - assets/images/quiz/LPFB(33).png
    - assets/images/quiz/LAFB(34).png
    - assets/images/quiz/AFL(37).png
    - assets/images/quiz/second_block_mobitz_i(38).png
    - assets/images/quiz/bradycardia(42).png
    - assets/images/quiz/Junctional_tachycardia(43).png
    - assets/images/quiz/vpc_bigeminy(44).png
    - assets/images/quiz/RBBB_LPFB(46).png
    - assets/images/quiz/Sinus_tachycardia_PVC_bigeminy(48).png
    - assets/images/quiz/bradyarrhythmia(52).png
    - assets/images/quiz/SSS(53).png
    - assets/images/quiz/2_1_AV_block(55).png
    - assets/images/quiz/Sustain_VT(56).png
    - assets/images/quiz/A_pacing_rhythm(61).png
    - assets/images/quiz/V_pacing_rhythm(62).png
    - assets/images/quiz/Afib_V_pacing(63).png
    - assets/images/quiz/high_degree_block(64).png
    - assets/images/quiz/first_AVblock_RBBB(65).png
    - assets/images/quiz/VT_induction(66).png
    - assets/images/quiz/SN_block(67).png
    - assets/images/quiz/vpc_bigeminy(68).png
    - assets/images/quiz/PSVT_right(69).png
    - assets/images/quiz/AVRT_LPS(70).png
    - assets/images/quiz/PSVT_AVNRT(71).png
    - assets/images/quiz/Junctional_bradycardia(72).png
    - assets/images/quiz/AIVR(73).png
    - assets/images/cases/Inferior_STEMI_with_LBBB.png
    - assets/images/cases/RCA_STEMI3.png
    - assets/images/cases/RBBB_with_LAFB.png
    - assets/images/cases/Juctional_with_VPC_bigeminy.png
    - assets/images/cases/flutter_tachydependentBBBz.png
    - assets/images/cases/RBBB_flutter.png
    - assets/images/cases/RCA_CTO_pmLAD_curplit_with_afib.png
    - assets/images/cases/Junction_with_hyperkalemia.png
    - assets/images/cases/DCMP(35).png
    - assets/images/cases/RCA_CTO(39).png
    - assets/images/drug/norepinephrine.png
    - assets/images/drug/magnesium_sulfate.png
    - assets/images/drug/lidocaine.png
    - assets/images/drug/epinephrine.png
    - assets/images/drug/dopamine.png
    - assets/images/drug/dobutamine.png
    - assets/images/drug/amiodarone.png
    - assets/images/drug/calcium_gluconate.png
    - assets/images/drug/sodium_bicarbonate.png
    - assets/images/drug/atropine.png
    - assets/images/drug/adenosine.png
    - assets/images/logo.png
    - assets/images/ACS.png
    - assets/images/STD.png
    - assets/images/STD1.png